DROP TABLE IF EXISTS vulns;
	CREATE TABLE vulns (
		id INT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(250) NOT NULL,
		severity VARCHAR(10) NOT NULL
	);
	
DROP TABLE IF EXISTS users;
	CREATE TABLE users (
		id INT AUTO_INCREMENT PRIMARY KEY,
		username VARCHAR(250) NOT NULL,
		email VARCHAR(250) NOT NULL,
		is_admin BOOLEAN NOT NULL
	);